project_id = "rlymnpiwizkohghvkuje"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[api.tls]
enabled = false

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv6"
port = 54323
max_header_length = 4096

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
file_size_limit = "50MiB"
image_transformation.enabled = true

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false
enable_sms_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
template.invite = "./supabase/templates/invite.html"
template.confirmation = "./supabase/templates/confirmation.html"
template.recovery = "./supabase/templates/recovery.html"
template.magic_link = "./supabase/templates/magic_link.html"
template.email_change = "./supabase/templates/email_change.html"

[auth.sms]
enable_signup = true
enable_confirmations = false
template = "Your code is {{ .Code }} ."

[[auth.providers.email]]
enabled = true

[[auth.providers.phone]]
enabled = true

[edge_runtime]
enabled = true
ip_version = "ipv4"
port = 54327
inspector_port = 8083

[functions.create-user]
verify_jwt = false

[functions.public-calendar]
verify_jwt = false

[functions.rate-limit]
verify_jwt = false