// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rlymnpiwizkohghvkuje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJseW1ucGl3aXprb2hnaHZrdWplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMTIyMTQsImV4cCI6MjA3Mzg4ODIxNH0.TQ6DCVpRztg9KjChOXhXJzF5G-AWVLZKoTUPHKF4sWU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});